default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:postgresql, :username) %>
  password: <%= Rails.application.credentials.dig(:postgresql, :password) %>
  host: <%= Rails.application.credentials.dig(:postgresql, :host) %>

development:
  <<: *default
  database: gymvault_development

test:
  <<: *default
  database: gymvault_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>


